CCDNForum\ForumBundle\Entity\BaseForum:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            unique: true
        readAuthorisedRoles:
            type: array
            column: read_authorised_roles
            nullable: true

