CCDNForum\ForumBundle\Entity\BaseCategory:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        listOrderPriority:
            type: integer
            column: list_order_priority
        readAuthorisedRoles:
            type: array
            column: read_authorised_roles
            nullable: true
    manyToOne:
        forum:
            targetEntity: CCDNForum\ForumBundle\Entity\Forum
            inversedBy: categories
            nullable: true
            joinColumn:
                name: fk_forum_id
                referencedColumnName: id
                onDelete: SET NULL
