CCDNForum\ForumBundle\Entity\Board:
    type: entity
    table: cc_forum_board
    oneToMany:
        topics:
            targetEntity: CCDNForum\ForumBundle\Entity\Topic
            mappedBy: board
            cascade: ["remove"]