
ccdn_forum_admin_category_list:
    pattern: /
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:listAction, _locale: en }

ccdn_forum_admin_category_create:
    pattern: /create
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:createAction, _locale: en }

ccdn_forum_admin_category_create_process:
    pattern: /create/process
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:createProcessAction, _locale: en }

ccdn_forum_admin_category_edit:
    pattern: /edit/{categoryId}
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:editAction, _locale: en }

ccdn_forum_admin_category_edit_process:
    pattern: /edit/{categoryId}/process
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:editProcessAction, _locale: en }

ccdn_forum_admin_category_delete:
    pattern: /delete/{categoryId}
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:deleteAction, _locale: en }

ccdn_forum_admin_category_delete_process:
    pattern: /delete/{categoryId}/process
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:deleteProcessAction, _locale: en }

ccdn_forum_admin_category_reorder_up:
    pattern: /reorder/{categoryId}/up
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:reorderAction, _locale: en, direction: 0 }

ccdn_forum_admin_category_reorder_down:
    pattern: /reorder/{categoryId}/down
    defaults: { _controller: ccdn_forum_forum.controller.admin_category:reorderAction, _locale: en, direction: 1 }
