
ccdn_forum_admin_forum_list:
    pattern: /
    defaults: { _controller: ccdn_forum_forum.controller.admin_forum:listAction, _locale: en }

ccdn_forum_admin_forum_create:
    pattern: /create
    defaults: { _controller: ccdn_forum_forum.controller.admin_forum:createAction, _locale: en }

ccdn_forum_admin_forum_create_process:
    pattern: /create/process
    defaults: { _controller: ccdn_forum_forum.controller.admin_forum:createProcessAction, _locale: en }

ccdn_forum_admin_forum_edit:
    pattern: /edit/{forumId}
    defaults: { _controller: ccdn_forum_forum.controller.admin_forum:editAction, _locale: en }

ccdn_forum_admin_forum_edit_process:
    pattern: /edit/{forumId}/process
    defaults: { _controller: ccdn_forum_forum.controller.admin_forum:editProcessAction, _locale: en }

ccdn_forum_admin_forum_delete:
    pattern: /delete/{forumId}
    defaults: { _controller: ccdn_forum_forum.controller.admin_forum:deleteAction, _locale: en }

ccdn_forum_admin_forum_delete_process:
    pattern: /delete/{forumId}/process
    defaults: { _controller: ccdn_forum_forum.controller.admin_forum:deleteProcessAction, _locale: en }