
ccdn_forum_moderator_post_lock:
    pattern: /{postId}/lock
    defaults: { _controller: ccdn_forum_forum.controller.moderator_post:lockAction, _locale: en }

ccdn_forum_moderator_post_unlock:
    pattern: /{postId}/unlock
    defaults: { _controller: ccdn_forum_forum.controller.moderator_post:unlockAction, _locale: en }

ccdn_forum_moderator_post_unlock_process:
    pattern: /{postId}/unlock/process
    defaults: { _controller: ccdn_forum_forum.controller.moderator_post:unlockProcessAction, _locale: en }

ccdn_forum_moderator_post_restore:
    pattern: /{postId}/restore
    defaults: { _controller: ccdn_forum_forum.controller.moderator_post:restoreAction, _locale: en }
