#
# CRUD
#
ccdn_forum_user_post_show:
    pattern: /{postId}
    defaults: { _controller: ccdn_forum_forum.controller.user_post:showAction, _locale: en, forumName: default }

ccdn_forum_user_post_edit:
    pattern: /{postId}/edit
    defaults: { _controller: ccdn_forum_forum.controller.user_post:editAction, _locale: en, forumName: default }

ccdn_forum_user_post_edit_process:
    pattern: /{postId}/edit/process
    defaults: { _controller: ccdn_forum_forum.controller.user_post:editProcessAction, _locale: en, forumName: default }

ccdn_forum_user_post_delete:
    pattern: /{postId}/delete
    defaults: { _controller: ccdn_forum_forum.controller.user_post:deleteAction, _locale: en, forumName: default }

ccdn_forum_user_post_delete_process:
    pattern: /{postId}/delete/process
    defaults: { _controller: ccdn_forum_forum.controller.user_post:deleteProcessAction, _locale: en, forumName: default }
